### ISSUE TITLE
Strength validation documentation

### ISSUE THREAD

**Issue by vladab** [rollerworks/PasswordStrengthBundle#67]
Does the 4th option maybe has also special character as a requirement?

There isn't any difference between 3rd and 4th option in the documentation, maybe I'm missing something?

https://github.com/rollerworks/PasswordStrengthBundle/blob/master/docs/strength-validation.md

**Comment by sstok** [comment]
It depends, the `PasswordStrength` works with a points system.
You can score a 3 and still have special characters.

Everything you do increases the score: lowercase, uppercase, special characters, numbers and length (more then 12).

`If the password consists of only numbers or a-z/A-Z the final strength decreases.`
This needs to be removed, because it's not really true anymore.
