### ISSUE TITLE
Some characters can override validation

### ISSUE THREAD

**Issue by naei** [rollerworks/PasswordStrengthBundle#68]
On v1.5.3, it seems possible to submit a form with a password not containing letter or number and with a length which is half of the one defined.

For example, with the following PasswordRequirements constraint: 
`@RollerworksPassword\PasswordRequirements(minLength=6, requireLetters=true, requireNumbers=true)`, with the password `²²²`: there is no warning, the form is submitted.

The `²` symbol seems to be considered as both a number and a letter, and its length evaluated as if it was 2 characters instead of 1.
The problem also happen with the accented letter `ù` (both of these characters are on French keyboards).

**Comment by sstok** [comment]
I don't have time to fix this atm, but if anyone is willing to provide a pull-request (with tests of course) I'll happy to review and merge 👍

**Comment by sstok** [comment]
I'm working on a fix, I was busy with [HubKit](https://github.com/park-manager/hubkit/) and got the flu directly after I was done 😑

The length problem is caused by strlen (which should be mb).

Concerning the problem with `²²²` I'm not entirely sure this is a legit problem as most brute-force crackers (to my knowledge) don't use foreign characters for the simpler attempts.
And http://lmgsecurity.com/blog/2016/04/18/brilliant-ways-hackers-crack-passwords-and-how-to-avoid-a-weak-password/ seems to recommend "Non-English characters, i.e. ü, ñ, ç, when possible".

It's a simple fix though, so I have no problem with changing this 🙃 but I need to be sure.

**Comment by sstok** [comment]
Length problem is solved with #70

**Comment by sstok** [comment]
Correction #70 solved the problem only for the strength validator but not the requirements validator 😅 I'm working on a fix.

**Comment by sstok** [comment]
Should be fixed by #78
