### ISSUE TITLE
Search P0wned password DB?

### ISSUE THREAD

**Issue by gnat42** [rollerworks/PasswordStrengthBundle#92]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | yes
| RFC?             | yes

I'm thinking of implementing password validation against https://haveibeenpwned.com/API/v2#SearchingPwnedPasswordsByRange

Basically I expect to hash the password, do a ranged search (pass the first 5 chars of the hash), you get back all hashes that start with those 5 chars, and a count of how many times this password has been seen in compromised databases. 

Is this something you'd accept as a PR to this bundle or should I implement it separately?

**Comment by sstok** [comment]
Interesting feature. If you can limit the package dependency to PSR it should be possible.
Anyone can choose which Http implementation they prefer.

Btw. Since v2.0 the bundle's purpose is to integrate the https://github.com/rollerworks/PasswordStrengthValidator and it doesn't have to be Symfony specific 👍

I would be willing to accept this to the library 👍

**Comment by sstok** [comment]
FYI. Symfony recently accepted a pr to introduce this validator in the Symfony Validator Component.
https://github.com/symfony/symfony/pull/27738
